version: '3.8'

services:
  eth:
    container_name: l2_messaging_eth
    build:
      context: .
      dockerfile: ./ethereum/Dockerfile.local
    healthcheck:
      test: ["CMD", "netstat", "-tuplen", "|", "grep", "8545"]
      interval: 1s
      timeout: 1s
      retries: 10
    volumes:
      - ./scripts/env:/tmp/env
    ports:
      - 8545:8545

  stark:
    container_name: l2_messaging_stark
    build:
      context: .
      dockerfile: ./starknet/Dockerfile.local
    volumes:
      - ./scripts/env:/tmp/env
    ports:
      - 5050:5050
    depends_on:
      eth:
        condition: service_healthy
