version: '3.8'

services:
  eth:
    container_name: l2_messaging_eth
    build:
      context: .
      dockerfile: ./ethereum/Dockerfile.local
    healthcheck:
      test: ["CMD", "netstat", "-tuplen", "|", "grep", "8545"]
      interval: 1s
      timeout: 1s
      retries: 10
    ports:
      - 8545:8545
    environment:
      - ETH_RPC_URL=http://localhost:8545
      - ETHERSCAN_API_KEY=0x1
      - ACCOUNT_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - ACCOUNT_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - CONTRACT_MSG_ADDRESS=0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
      - SN_MESSAGING_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
      - L2_CONTRACT_ADDRESS=0x05528d572fdd2e8f9d5e3fafda3b038fdfff6188d6797f6096004c941d080800
      - L2_SELECTOR_VALUE=0x005421de947699472df434466845d68528f221a52fce7ad2934c5dae2e1f1cdc
      - L2_SELECTOR_STRUCT=0x00f1149cade9d692862ad41df96b108aa2c20af34f640457e781d166c98dc6b0
      - L2_ACCOUNT=0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973

  stark:
    container_name: l2_messaging_stark
    build:
      context: .
      dockerfile: ./starknet/Dockerfile.local
    depends_on:
      eth:
        condition: service_healthy
    ports:
      - 5050:5050

# zksync_geth:
#   container_name: l2_messaging_zksync_geth
#   image: "matterlabs/geth:latest"
#   logging:
#       driver: none 
#   ports:
#     - "8545:8545"
#     - "8546:8546"

  zksync_db:
    container_name: l2_messaging_zksync_db
    image: "postgres:12"
    logging:
      driver: none 
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  zksync:
    container_name: l2_messaging_zksync
    stdin_open: true
    tty: true
    image: matterlabs/local-node:latest2.0
    depends_on:
      - eth
      - zksync_db
    ports:
      - "3050:3050" # JSON RPC HTTP port
      - "3051:3051" # JSON RPC WS port
    environment:
      - DATABASE_URL=postgres://postgres@zksync_db/zksync_local
      - ETH_CLIENT_WEB3_URL=http://eth:8545
